# Generated by Django 5.2.1 on 2025-05-24 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0003_alter_notificationbot_auth_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationbot',
            name='notification_time',
        ),
    ]
